### ISSUE TITLE
BAS Generation Issue

### ISSUE THREAD

**Issue by attilaberencsi** [sanjoy0308/generator-hanaCloudUI5#1]
Hi Sanjoy,
when trying to run the generator, I am getting the following issue in BAS:

![image](https://user-images.githubusercontent.com/20442467/233102586-73ffd982-3a93-4739-a216-d1179db01c19.png)

It seems instead of the linux path separator (forward slash) the backward slash is used. This is working on windows on VSCode but not in BAS.

Could You please check.

Thank You

Best regards

Attila

**Comment by sanjoy0308** [comment]
Hi Attila,

BAS is not in scope as it is licensed product, and I don't have access to.

Kind Regards,
Sanjoy
